package:
  name: cargo-c
  version: 0.10.0
  epoch: 0
  description: build and install C-compatible libraries
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - openssl-dev
      - rust

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/lu-zero/cargo-c
      tag: v${{package.version}}
      expected-commit: 62e72d44915675b2678f32e701bc1503d32881bb

  - runs: |
      cargo build --release
      install -Dm755 target/release/cargo-capi "${{targets.destdir}}"/usr/bin/cargo-capi
      install -Dm755 target/release/cargo-cbuild "${{targets.destdir}}"/usr/bin/cargo-cbuild
      install -Dm755 target/release/cargo-cinstall "${{targets.destdir}}"/usr/bin/cargo-cinstall
      install -Dm755 target/release/cargo-ctest "${{targets.destdir}}"/usr/bin/cargo-ctest

  - uses: strip

update:
  enabled: true
  github:
    identifier: lu-zero/cargo-c
    strip-prefix: v
