package:
  name: cloudnative-pg
  version: 1.23.2
  epoch: 0
  description: CloudNativePG is a comprehensive platform designed to seamlessly manage PostgreSQL databases
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/cloudnative-pg/cloudnative-pg
      tag: v${{package.version}}
      expected-commit: 4bef841286ef84c4b435a6204a7ee632e1d4fb57

  - uses: go/build
    with:
      modroot: ./cmd/manager
      output: manager
      packages: .

  - uses: strip

subpackages:
  - name: ${{package.name}}-plugins
    pipeline:
      - uses: go/build
        with:
          packages: ./cmd/kubectl-cnpg
          output: plugins
          subpackage: true

update:
  enabled: true
  github:
    identifier: cloudnative-pg/cloudnative-pg
    strip-prefix: v
    use-tag: true

test:
  environment:
    contents:
      packages:
        - busybox
  pipeline:
    # - Testing observability requires helm installation
    # - Testing backup and Recovery requires using BarmanObjectStorage:
    - name: "Verify Installation"
      runs: |
        manager version | grep "${{package.version}}"
