package:
  name: kor
  version: 0.5.0
  epoch: 0
  description: A Golang Tool to discover unused Kubernetes Resources
  copyright:
    - license: MIT

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/yonahd/kor
      tag: v${{package.version}}
      expected-commit: a2f3629e7738e8013ddaa470da5f6cde434ebef3

  - uses: go/build
    with:
      modroot: .
      packages: .
      output: kor

  - uses: strip

update:
  enabled: true
  github:
    identifier: yonahd/kor
    strip-prefix: v
