package:
  name: lz4
  version: 1.9.4
  epoch: 5
  description: "lossless high performance compression algorithm"
  copyright:
    - license: BSD-2-Clause AND GPL-2.0-only

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/lz4/lz4
      tag: v${{package.version}}
      expected-commit: 5ff839680134437dbf4678f3d0c7b371d84f4964

  - runs: |
      make -j$(nproc) CC=${{host.triplet.gnu}}-gcc

  - runs: |
      make install PREFIX="/usr" DESTDIR="${{targets.destdir}}"

  - uses: strip

subpackages:
  - name: "lz4-doc"
    description: "lz4 documentation"
    pipeline:
      - uses: split/manpages
      - uses: split/infodir

  - name: "lz4-static"
    description: "lz4 static library"
    pipeline:
      - uses: split/static

  - name: "lz4-dev"
    description: "lz4 development headers"
    pipeline:
      - uses: split/dev

  - name: "liblz4-1"
    description: "lz4 runtime libraries"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/lib
          mv "${{targets.destdir}}"/usr/lib/liblz4.so.* "${{targets.subpkgdir}}"/usr/lib/

update:
  enabled: true
  github:
    identifier: lz4/lz4
    strip-prefix: v
    tag-filter: v
