package:
  name: patroni
  version: 3.3.1
  epoch: 0
  description: Patroni is a template for high availability (HA) PostgreSQL solutions using Python.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - py3-boto3
      - py3-psycopg

environment:
  contents:
    packages:
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-boto3
      - py3-psycopg
      - py3.12-pip
      - python3-dev

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 9ffc4fc3a99bbfef3cb8ca4b3963cbc53f6319ed
      repository: https://github.com/zalando/patroni
      tag: v${{package.version}}

  - name: Python Build
    runs: |
      pip install patroni[psycopg3,all] --root=${{targets.destdir}} --prefix=/usr

update:
  enabled: true
  github:
    identifier: zalando/patroni
    strip-prefix: v
    tag-filter: v

test:
  pipeline:
    - name: Verify patroni installation
      runs: |
        patroni --version
