package:
  name: php-8.1-grpc
<<<<<<< HEAD
  version: 1.63.0
  epoch: 1
=======
  version: 1.64.2
  epoch: 0
>>>>>>> 7b41f0f0c (php-8.1-grpc/1.64.2 package update)
  description: "A PHP extension for gRPC"
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ${{package.name}}-config
      - grpc
      - php-8.1

environment:
  contents:
    packages:
      - autoconf
      - build-base
      - busybox
      - grpc-dev
      - php-8.1
      - php-8.1-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/grpc/grpc
      tag: "v${{package.version}}"
      expected-commit: 4795c5e69b25e8c767b498bea784da0ef8c96fd5

  - name: Prepare build
    runs: cd src/php/ext/grpc && phpize

  - name: Configure
    runs: cd src/php/ext/grpc && ./configure

  - name: Make install
    runs: |
      cd src/php/ext/grpc
      INSTALL_ROOT="${{targets.destdir}}" DESTDIR="${{targets.destdir}}" make install

subpackages:
  - name: ${{package.name}}-config
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}/etc/php/conf.d"
          echo "extension=grpc.so" > "${{targets.subpkgdir}}/etc/php/conf.d/grpc.ini"

update:
  enabled: true
  github:
    identifier: grpc/grpc
    strip-prefix: v
    tag-filter: v
