package:
  name: py3-tenacity
  version: 8.4.1
  epoch: 0
  description: "General-purpose retrying library, written in Python, to simplify the task of adding retry behavior to just about anything"
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/jd/tenacity.git
      tag: ${{package.version}}
      expected-commit: ee6a8f7a76654d712fd44604d3b6d4f9af6b2249

  - uses: python/build-wheel

  - uses: strip

update:
  enabled: true
  github:
    identifier: jd/tenacity
    use-tag: true
  ignore-regex-patterns:
    - 'mergify2-'
