package:
  name: py3-urllib3-1
  version: 1.26.19
  epoch: 0
  description: "HTTP library with thread-safe connection pooling, file post, and more"
  copyright:
    - license: MIT
  dependencies:
    provides:
      - py3-urllib3=1.999
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-gpep517
      - py3-setuptools
      - py3-wheel

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/urllib3/urllib3.git
      tag: ${{package.version}}
      expected-commit: d9d85c88aa644af56d5e129634e750ce76e1a765

  - runs: |
      python3 -m gpep517 build-wheel \
        --wheel-dir dist \
        --output-fd 3 3>&1 >&2

  - runs: |
      python3 -m installer -d "${{targets.destdir}}" dist/*.whl

  - uses: strip

update:
  enabled: true
  ignore-regex-patterns:
    - (\d+\.\d+)\.\da\d+ # urllib3 releases alpha versions with a suffix "a" followed by a digit, let's ignore these
  github:
    identifier: urllib3/urllib3
    use-tag: true
    tag-filter: "1"
