package:
  name: restic
  version: 0.16.4
  epoch: 12
  description: restic is a backup program which allows saving multiple revisions of files and directories in an encrypted repository stored on different backends
  copyright:
    - license: BSD-2-Clause

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/restic/restic
      tag: v${{package.version}}
      expected-commit: 3786536dc18ef27aedcfa8e4c6953b48353eee79

  - uses: go/bump
    with:
      deps: google.golang.org/protobuf@v1.33.0 golang.org/x/net@v0.23.0 github.com/Azure/azure-sdk-for-go/sdk/azidentity@v1.6.0

  - uses: go/build
    with:
      packages: ./cmd/restic
      output: restic
      ldflags: "-X main.version=${{package.version}}"

subpackages:
  - name: ${{package.name}}-compat
    description: "Compatibility package to place binaries in the location expected by upstream helm charts"
    pipeline:
      - runs: |
          # The helm chart expects the binaries to be in / instead of /usr/bin
          mkdir -p "${{targets.subpkgdir}}"
          ln -sf /usr/bin/restic ${{targets.subpkgdir}}/restic

update:
  enabled: true
  github:
    identifier: restic/restic
    strip-prefix: v

test:
  pipeline:
    - runs: |
        restic version
