package:
  name: zarf
  version: 0.35.0
  epoch: 0
  description: DevSecOps for Air Gap & Limited-Connection Systems.
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - busybox
      - ca-certificates-bundle
      - go
      - nodejs

pipeline:
  - uses: git-checkout
    with:
      expected-commit: c8abe31a5c4bbed933d692fcdeeefdc4b31701a5
      repository: https://github.com/defenseunicorns/zarf
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: github.com/sigstore/cosign/v2@v2.2.4 github.com/Azure/azure-sdk-for-go/sdk/azidentity@v1.6.0
      replaces: github.com/prometheus/common=github.com/prometheus/common@v0.45.0 github.com/prometheus/client_golang=github.com/prometheus/client_golang@v1.18.0 github.com/mholt/archiver/v3=github.com/anchore/archiver/v3@v3.5.2
      show-diff: true

  - uses: go/build
    with:
      ldflags: -s -w -X 'github.com/defenseunicorns/zarf/src/config.CLIVersion=v${{package.version}}'
      output: zarf
      packages: .

  - uses: strip

test:
  pipeline:
    - runs: |
        zarf version || exit 1

update:
  enabled: true
  github:
    identifier: defenseunicorns/zarf
    strip-prefix: v
